### ISSUE TITLE
Unable to create varied question types in LimeSurvey

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/infrastructure#2]
I've gone through the tutorial, but can't figure out how to add various types of questions (such as multiple choice, radio buttons, etc.) along with the default text questions/answers.

**Comment by foundscapes** [comment]
I found a place where I can choose what type of question, but can't figure out how to add in the question details for each multiple choice option in this case. Ex for contact info.: email, signal, wire, whatsapp, other
![screen shot 2018-05-31 at 4 59 14 pm](https://user-images.githubusercontent.com/2231711/40814287-33c05f32-64f4-11e8-95c1-6364bdb5c48e.png)

**Comment by mattl** [comment]
Once the question is saved, you'll need to add either subquestions or answer choices based on the kind of question. For a multiple choice (subquestions) vs a single choice (answer choices)

![screen shot 2018-06-01 at 12 46 33 pm](https://user-images.githubusercontent.com/33296/40852874-000fa516-659a-11e8-9bd9-8483d833ddd9.png)
![screen shot 2018-06-01 at 12 46 25 pm](https://user-images.githubusercontent.com/33296/40852875-001e2988-659a-11e8-8ce7-20e8e96acfd3.png)
![screen shot 2018-06-01 at 12 46 12 pm](https://user-images.githubusercontent.com/33296/40852877-002c455e-659a-11e8-86e9-e4ef4c6782e2.png)

**Comment by foundscapes** [comment]
How did you customize the answers/radio buttons, I don't see anywhere to do that or add answers
![screen shot 2018-06-01 at 2 56 34 pm](https://user-images.githubusercontent.com/2231711/40865266-56576a78-65ac-11e8-9217-8b06f59bf058.png)

**Comment by foundscapes** [comment]
FIGURED IT OUT, the UX is baaad
